---
title: "HW 2 R Notebook"
output:
  word_document: default
  html_notebook: default
---

problem 4. 
```{r}
#create a dataframe from mtcars
data.frame(mtcars)
#calculate the correlation between weight and mgp of cars
cor(mtcars$wt,mtcars$mpg)
#plot the points of weight and mpg of cars
plot(mtcars$wt,mtcars$mpg)
```
problem 5
```{r}

#read in the data from the CSV file. 
data <-read.csv("C:/Users/vpool/Documents/Winter2024/CSC587DataMining/datasets/DATA/metabolite.csv")
#Set percent oi missing values 
cutOff <- 0.75 
#calculate the missing value for each column 

#create new dataset with the subset of all the rows and only columns on the percentage of missing values 
newData <- subset(data, select = colMeans(is.na(data)) < cutOff)

#testing to see which column had missing data 
#newData[ ,!complete.cases(newData)]
medValue <- rep(NA,ncol(newData)) 
#for each col in newdata calculate the median value from only values that are not NA, then replace the NA value with the medianvalue calculated 
for(col in names(newData)){
  medValue[col] <- median(newData[[col]], na.rm = TRUE)
  newData[is.na(newData[[col]]), col] <-medValue[col]
  
}
#testing to confirm if there are no missing values 
#newData[ ,!complete.cases(newData)]
#(newData)



```
problem 6
```{r}
library(ggplot2,tidyverse)
#pull out data from new data
subNewData <- newData[ ,2:188]
#convert non numeric values to numeric there was char data in the dataset 
subNewData [ ,sapply(subNewData, function(x) !is.numeric(x))] <- sapply(subNewData[, sapply(subNewData, function(x) !is.numeric(x))], as.numeric)

#do a PRC and store in dataPCA
dataPca <- prcomp(subNewData)
#convert the PCA in to a dataframe 
dataMap <- as.data.frame(dataPca$x)


head(dataPca)
#plt thje PCA PC1 and PC2 with the collars based on the labels 
ggplot(data = dataMap,aes(x = PC1, y = PC2)) + geom_point(aes(color=newData$Label))
```
